name: Java Unit/Integration Testing with Dockerized PostgreSQL

on:
  push:
    branches:
      - main
      - 'testingcontrollersbranch'

jobs:
  testing:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Update package lists and resolve dependency issues
      - name: Update package lists and resolve dependency issues
        run: |
          sudo apt-get update
          sudo apt-get remove -y containerd.io
          sudo apt-get install -y docker.io

      # Pull PostgreSQL Docker image
      - name: Pull PostgreSQL Docker image
        run: |
          sudo docker pull postgres:latest

      # Run PostgreSQL container
      - name: Run PostgreSQL container
        run: |
          sudo docker run -d --name postgres-container -e POSTGRES_DB=FinancialTrackerBeans -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=password -p 5432:5432 postgres:latest

      # Wait for PostgreSQL to start
      - name: Wait for PostgreSQL to start
        run: |
          until sudo docker exec postgres-container pg_isready -U postgres; do
            echo "Waiting for PostgreSQL to start..."
            sleep 1
          done

      # Copy SQL script to PostgreSQL container
      - name: Copy SQL script to PostgreSQL container
        run: |
          sudo docker cp ./database/SQL/BeansFinancialTrackerTables.sql postgres-container:/tmp/BeansFinancialTrackerTables.sql

      # Run SQL scripts on PostgreSQL container
      - name: Run SQL scripts on PostgreSQL container
        run: |
          sudo docker exec -i postgres-container psql -U postgres -d FinancialTrackerBeans -f /tmp/BeansFinancialTrackerTables.sql

      # Run Unit Tests
      - name: Run Unit Tests
        run: mvn test
